spring:
  application:
    name: Note-spring-api
  data:
    mongodb:
      uri: mongodb://mongo:NrQdnPknqQXzAQNTtjIDRFxnhCHCHVRh@shortline.proxy.rlwy.net:48170/notesdb?authSource=admin

server:
  port: 8080