spring:
  application:
    name: Note-spring-api
  data:
    mongodb:
      uri: ${MongoDB.MONGO_URL:mongodb://mongo:NrQdnPknqQXzAQNTtjIDRFxnhCHCHVRh@mongodb.railway.internal:27017}
      password: NrQdnPknqQXzAQNTtjIDRFxnhCHCHVRh
      host: mongodb.railway.internal
      port: 27017
      username: mongo

server:
  port: 8080