spring:
  application:
    name: Note-spring-api
  data:
    mongodb:
      uri: ${MongoDB.MONGO_URL:mongodb://mongo:NrQdnPknqQXzAQNTtjIDRFxnhCHCHVRh@shortline.proxy.rlwy.net:48170}

server:
  port: 8080