spring:
  application:
    name: Note-spring-api
  data:
    mongodb:
      uri: mongodb://mongo:NrQdnPknqQXzAQNTtjIDRFxnhCHCHVRh@mongodb.railway.internal:27017/notesdb?authSource=admin

server:
  port: 8080